// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type List struct {
	ID    string      `json:"id"`
	Name  string      `json:"name"`
	Items []*ListItem `json:"items"`
}

type ListItem struct {
	ID   string `json:"id"`
	Data string `json:"data"`
}

type NewList struct {
	Name  string   `json:"name"`
	Items []string `json:"items"`
}

type NewListItems struct {
	ListID string   `json:"listId"`
	Items  []string `json:"items"`
}
